### ISSUE TITLE
Signal safety?

### ISSUE THREAD

**Issue by akhilles** [stjepang/async-channel#17]
From my initial inspection, it looks like `Sender::try_send` is safe to use inside signal handlers. If this is case, it might be worth documenting since it's a compelling alternative to `signal_hook::iterator::Signals`.

**Comment by stjepang** [comment]
Not quite - `Sender::try_send()` might allocate, and allocation might grab an internal lock inside the allocator, do syscalls etc. So it's definitely not signal safe :)
