### ISSUE TITLE
Expose `sender_count` and `receiver_count`

### ISSUE THREAD

**Issue by EliSnow** [stjepang/async-channel#18]
I'm looking to migrate a piece of code from a custom channel implementation to async-channel, but one important need is the ability to have statistics about the channels (including sender and receiver count). I see the `Channel` struct [has that data](https://github.com/stjepang/async-channel/blob/d23f31f1e2fdde7b4388c6fb37ca3a090a4d04dc/src/lib.rs#L59), but it doesn't appear to be exposed on either `Sender` or `Receiver`.

Would you be amenable to a PR which adds:

```rust
pub fn sender_count(&self) -> usize;
pub fn receiver_count(&self) -> usize;
```

to both `Sender` and `Receiver`?

**Comment by stjepang** [comment]
I would, that sounds reasonable! It'd be very similar to `Arc::strong_count()` and `Arc::weak_count()`.
